export const products = [
  {
    id: 1,
    name: "Laptop",
    typology: "Electronics",
    price: 1200.99,
    description: "High-performance laptop with SSD and 16GB RAM.",
  },
  {
    id: 2,
    name: "Smartphone",
    typology: "Electronics",
    price: 899.49,
    description: "Latest model smartphone with OLED display.",
  },
  {
    id: 3,
    name: "Tablet",
    typology: "Electronics",
    price: 499.99,
    description: "Lightweight tablet with 10-inch screen.",
  },
  {
    id: 4,
    name: "Smartwatch",
    typology: "Electronics",
    price: 199.99,
    description: "Fitness tracking smartwatch with GPS.",
  },
  {
    id: 5,
    name: "Wireless Headphones",
    typology: "Electronics",
    price: 149.99,
    description: "Noise-canceling wireless headphones.",
  },
  {
    id: 6,
    name: "Desk Chair",
    typology: "Furniture",
    price: 249.99,
    description: "Ergonomic office chair with lumbar support.",
  },
  {
    id: 7,
    name: "Office Desk",
    typology: "Furniture",
    price: 399.99,
    description: "Spacious wooden office desk.",
  },
  {
    id: 8,
    name: "Bookshelf",
    typology: "Furniture",
    price: 129.99,
    description: "5-tier bookshelf for storage.",
  },
  {
    id: 9,
    name: "Table Lamp",
    typology: "Furniture",
    price: 39.99,
    description: "Modern LED table lamp with adjustable brightness.",
  },
  {
    id: 10,
    name: "Sofa",
    typology: "Furniture",
    price: 899.99,
    description: "Comfortable three-seater sofa.",
  },
  {
    id: 11,
    name: "Running Shoes",
    typology: "Clothing",
    price: 79.99,
    description: "Breathable and lightweight running shoes.",
  },
  {
    id: 12,
    name: "T-Shirt",
    typology: "Clothing",
    price: 19.99,
    description: "Cotton T-shirt available in various colors.",
  },
  {
    id: 13,
    name: "Jeans",
    typology: "Clothing",
    price: 49.99,
    description: "Classic fit denim jeans.",
  },
  {
    id: 14,
    name: "Jacket",
    typology: "Clothing",
    price: 89.99,
    description: "Warm and stylish winter jacket.",
  },
  {
    id: 15,
    name: "Backpack",
    typology: "Clothing",
    price: 59.99,
    description: "Durable and waterproof backpack.",
  },
  {
    id: 16,
    name: "Blender",
    typology: "Home Appliances",
    price: 69.99,
    description: "High-speed blender for smoothies and soups.",
  },
  {
    id: 17,
    name: "Microwave",
    typology: "Home Appliances",
    price: 199.99,
    description: "Compact microwave with multiple settings.",
  },
  {
    id: 18,
    name: "Vacuum Cleaner",
    typology: "Home Appliances",
    price: 299.99,
    description: "Powerful vacuum cleaner with HEPA filter.",
  },
  {
    id: 19,
    name: "Air Fryer",
    typology: "Home Appliances",
    price: 129.99,
    description: "Oil-free air fryer for healthy cooking.",
  },
  {
    id: 20,
    name: "Coffee Maker",
    typology: "Home Appliances",
    price: 79.99,
    description: "Automatic coffee maker with timer.",
  },
];
